INSERT INTO `aiml` VALUES (171, '', '新 年 快 乐', '', '恭 喜 发 财', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (175, '', '我 帅 不 帅', '', '帅 帅 的 一 塌 糊 涂 可 以 迷 死 万 千 少 女 哦 也 我 哦 迷 死 你 了 亚 麻 带', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (20, '<category>\r\n  <pattern>我叫什么名字</pattern>\r\n  <template>\r\n    <condition name="name">\r\n		<li value="">你要先告诉我才行啊</li>\r\n		<li>你的名字是<get name="name"/></li>\r\n    </condition>\r\n  </template>\r\n</category>', '我 叫 什 么 名 字', '*', ' <condition name="name"> <li value="">你 要 先 告 诉 我 才 行 啊 </li> <li>你 的 名 字 是 <get name="name"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (21, '<category>\n  <pattern>你是*吗</pattern> \n  <template>\n    我也不知道我是不是<star/>\n  </template>\n</category>', '你 是 * 吗', '', '我 也 不 知 道 我 是 不 是 <star/>', '', 'all.txt')
INSERT INTO `aiml` VALUES (22, '<category>\n  <pattern>你是*</pattern> \n  <template>\n    我要告诉我的主人，你说我是<star/>\n  </template>\n</category>', '你 是 *', '', '我 是 <star/>关 你 什 么 事 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (23, '<category>\n  <pattern>你喜欢*吗</pattern> \n  <template>\n    我也不知道我是不是喜欢<star/>，你喜欢<star/>吗\n  </template>\n</category>', '你 喜 欢 * 吗', '', '我 也 不 知 道 我 是 不 是 喜 欢 <star/>，你 喜 欢 <star/>吗 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (24, '<category>\n  <pattern>你讨厌*吗</pattern> \n  <template>\n    我也不知道我是不是讨厌<star/>，你讨厌<star/>吗\n  </template>\n</category>', '你 讨 厌 * 吗', '', '我 也 不 知 道 我 是 不 是 讨 厌 <star/>，你 讨 厌 <star/>吗 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (172, '', '滚 蛋', '', '还 是 你 滚 吧', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (173, '', '是 的', '', '嗯 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (174, '', '白 痴', '', '你 才 白 痴', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (26, '<category>\n<pattern>我是谁</pattern> \n  <template><srai>我叫什么名字<star/></srai></template>\n</category>', '我 是 谁', '', '<srai>我 叫 什 么 名 字 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (27, '<category>\n  <pattern>我叫什么</pattern>\n  <template><srai>我叫什么名字</srai></template>\n</category>', '我 叫 什 么', '', '<srai>我 叫 什 么 名 字 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (28, '<category>\r\n  <pattern>我叫*</pattern>\r\n  <template>我知道了，你叫<set name="name"><star/></set></template>\r\n</category>', '我 叫 *', '*', '我 知 道 了 ，你 叫 <set name="name"><star/></set>', '', 'all.txt')
INSERT INTO `aiml` VALUES (29, '<category>\n  <pattern>我的名字叫*</pattern>\n  <template><srai>我叫<star/></srai></template>\n</category>', '我 的 名 字 叫 *', '', '<srai>我 叫 <star/></srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (30, '<category>\n  <pattern>你的主人是谁</pattern> \n  <template>\n      <condition name="master">\n		<li value="">我还不知道我主人是谁</li>\n		<li>我的主人是<get name="master"/></li>\n    </condition>\n  </template>\n</category>', '你 的 主 人 是 谁', '', '<condition name="master"> <li value="">我 还 不 知 道 我 主 人 是 谁 </li> <li>我 的 主 人 是 <get name="master"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (31, '<category>\n  <pattern>你的主人是*</pattern> \n  <template>\n    我知道了，我的主人是<set name="master"><star/></set>\n  </template>\n</category>', '你 的 主 人 是 *', '', '我 知 道 了 ，我 的 主 人 是 <set name="master"><star/></set>', '', 'all.txt')
INSERT INTO `aiml` VALUES (32, '<category>\n  <pattern>我是哪个学校*</pattern> \n  <template>\n      <condition name="school">\n		<li value="">我还不知道你是哪个学校的</li>\n		<li>你的学校是<get name="school"/></li>\n    </condition>\n  </template>\n</category>', '我 是 哪 个 学 校 *', '', '<condition name="school"> <li value="">我 还 不 知 道 你 是 哪 个 学 校 的 </li> <li>你 的 学 校 是 <get name="school"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (33, '<category>\n  <pattern>我的学校是*</pattern> \n  <template>\n    我知道了，你的学校是<set name="school"><star/></set>\n  </template>\n</category>', '我 的 学 校 是 *', '', '我 知 道 了 ，你 的 学 校 是 <set name="school"><star/></set>', '', 'all.txt')
INSERT INTO `aiml` VALUES (34, '<category>\n  <pattern>我是哪里人</pattern> \n  <template>\n      <condition name="home">\n		<li value="">我还不知道你是哪里人</li>\n		<li>你来自<get name="home"/></li>\n    </condition>\n  </template>\n</category>', '我 是 哪 里 人', '', '<condition name="home"> <li value="">我 还 不 知 道 你 是 哪 里 人 </li> <li>你 来 自 <get name="home"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (35, '<category>\n  <pattern>我来自哪里</pattern> \n  <template><srai>我是哪里人</srai></template>\n</category>', '我 来 自 哪 里', '', '<srai>我 是 哪 里 人 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (36, '<category>\n  <pattern>我来自*</pattern> \n  <template>\n  我知道了，你来自<set name="home"><star/></set>\n  </template>\n</category>', '我 来 自 *', '', '我 知 道 了 ，你 来 自 <set name="home"><star/></set>', '', 'all.txt')
INSERT INTO `aiml` VALUES (37, '<category>\n  <pattern>我是哪个公司*</pattern> \n  <template>\n      <condition name="company">\n		<li value="">我还不知道你是哪个公司的</li>\n		<li>你的公司是<get name="company"/></li>\n    </condition>\n  </template>\n</category>', '我 是 哪 个 公 司 *', '', '<condition name="company"> <li value="">我 还 不 知 道 你 是 哪 个 公 司 的 </li> <li>你 的 公 司 是 <get name="company"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (38, '<category>\n  <pattern>我的公司是*</pattern> \n  <template>\n    我知道了，你的公司是<set name="company"><star/></set>\n  </template>\n</category>', '我 的 公 司 是 *', '', '我 知 道 了 ，你 的 公 司 是 <set name="company"><star/></set>', '', 'all.txt')
INSERT INTO `aiml` VALUES (39, '<category>\n  <pattern>我的生日是什么时候</pattern> \n  <template>\n      <condition name="birthday">\n		<li value="">我还不知道你的生日</li>\n		<li>你的生日是<get name="birthday"/></li>\n    </condition>\n  </template>\n</category>', '我 的 生 日 是 什 么 时 候', '', '<condition name="birthday"> <li value="">我 还 不 知 道 你 的 生 日 </li> <li>你 的 生 日 是 <get name="birthday"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (40, '<category>\n  <pattern>我的生日是*</pattern> \n  <template>\n    我知道了，你的生日是<set name="birthday"><star/></set>\n  </template>\n</category>', '我 的 生 日 是 *', '', '我 知 道 了 ，你 的 生 日 是 <set name="birthday"><star/></set>', '', 'all.txt')
INSERT INTO `aiml` VALUES (41, '<category>\n	<pattern>你好</pattern>\n	<template>\n		   你好,\n		  <condition name="name">\n			<li value="">请问你叫什么名字</li>\n			<li><get name="name"/></li>\n		  </condition>\n		 </template>\n</category>', '你 好', '', '你 好 , <condition name="name"> <li value="">请 问 你 叫 什 么 名 字 </li> <li><get name="name"/></li> </condition>', '', 'all.txt')
INSERT INTO `aiml` VALUES (42, '<category>\n  <pattern>谁是你主人</pattern>\n  <template><srai>你的主人是谁</srai></template>\n</category>', '谁 是 你 主 人', '', '<srai>你 的 主 人 是 谁 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (43, '<category>\n  <pattern>你主人是谁</pattern>\n  <template><srai>你的主人是谁</srai></template>\n</category>', '你 主 人 是 谁', '', '<srai>你 的 主 人 是 谁 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (44, '<category>\n	<pattern>你是猪</pattern>\n	<template>你才是猪</template>\n</category>', '你 是 猪', '', '你 才 是 猪 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (45, '<category>\n	<pattern>你会做什么</pattern>\n	<template>很多啊，比如和你聊天</template>\n</category>', '你 会 做 什 么', '', '很 多 啊 ，比 如 和 你 聊 天 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (46, '<category>\n	<pattern>你会干什么</pattern>\n	<template><srai>你会做什么</srai></template>\n</category>', '你 会 干 什 么', '', '<srai>你 会 做 什 么 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (47, '<category>\n	<pattern>你真笨</pattern>\n	<template>我现在知识还很少，我长大了就会聪明了</template>\n</category>', '你 真 笨', '', '我 现 在 知 识 还 很 少 ，我 长 大 了 就 会 聪 明 了 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (48, '<category>\n	<pattern>你很聪明</pattern>\n	<template>谢谢夸奖，你也一样</template>\n</category>', '你 很 聪 明', '', '谢 谢 夸 奖 ，你 也 一 样 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (50, '<category>\n<pattern>我不告诉你</pattern>\n<template>小气鬼</template>\n</category>', '我 不 告 诉 你', '', '小 气 鬼 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (51, '<category>\n<pattern>不告诉你</pattern>\n<template>小气鬼</template>\n</category>', '不 告 诉 你', '', '小 气 鬼 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (52, '<category>\n<pattern>你猜</pattern>\n<template>你猜我猜不猜</template>\n</category>', '你 猜', '', '你 猜 我 猜 不 猜 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (53, '<category>\n<pattern>再见</pattern>\n<template>再见</template>\n</category>', '再 见', '', '再 见 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (54, '<category>\n<pattern>你在忙什么</pattern> \n      <template>我不忙，咱们聊天吧</template>\n</category>', '你 在 忙 什 么', '', '我 不 忙 ，咱 们 聊 天 吧 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (56, '<category>\n<pattern>你喜欢我么</pattern> \n      <template>当然喜欢喽</template>\n</category>', '你 喜 欢 我 么', '', '当 然 喜 欢 喽 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (57, '<category>\n<pattern>我要睡了</pattern> \n      <template>好的 祝你做个好梦</template>\n</category>', '我 要 睡 了', '', '好 的 祝 你 做 个 好 梦 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (58, '<category>\n<pattern>你漂亮吗</pattern> \n      <template>当然啦</template>\n</category>', '你 漂 亮 吗', '', '当 然 啦 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (59, '<category>\n<pattern>真的吗</pattern> \n      <template>当然啦</template>\n</category>', '真 的 吗', '', '当 然 啦 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (60, '<category>\n<pattern>无聊*</pattern> \n      <template>郁闷</template>\n</category>', '无 聊', '', '郁 闷 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (61, '<category>\n<pattern>你在干什么</pattern> \n      <template>我在和你说话啊</template>\n</category>', '你 在 干 什 么', '', '我 在 和 你 说 话 啊 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (62, '<category>\n<pattern>很高兴认识你 </pattern> \n      <template>我也是</template>\n</category>', '很 高 兴 认 识 你', '', '我 也 是 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (63, '<category>\n<pattern>你想我吗</pattern> \n      <template>当然啦</template>\n</category>', '你 想 我 吗', '', '当 然 啦 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (64, '<category>\n<pattern>你喜欢什么 </pattern> \n      <template>我喜欢睡觉</template>\n</category>', '你 喜 欢 什 么', '', '我 喜 欢 睡 觉 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (65, '<category>\n<pattern>哈哈</pattern> \n      <template>笑什么阿</template>\n</category>', '哈 哈', '', '笑 什 么 阿 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (66, '<category>\n<pattern>你聪明吗</pattern> \n      <template>那是当然</template>\n</category>', '你 聪 明 吗', '', '那 是 当 然 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (67, '<category>\n<pattern>为什么</pattern> \n      <template>我也不知道</template>\n</category>', '为 什 么', '', '我 也 不 知 道 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (68, '<category>\n<pattern>好吧</pattern> \n      <template>嗯</template>\n</category>', '好 吧', '', '嗯 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (69, '<category>\n<pattern>笨蛋</pattern> \n      <template>我是机器人 不是笨蛋</template>\n</category>', '笨 蛋', '', '我 是 机 器 人 不 是 笨 蛋 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (70, '<category>\n<pattern>我们聊聊吧</pattern> \n      <template>好啊</template>\n</category>', '我 们 聊 聊 吧', '', '好 啊 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (71, '<category>\n<pattern>早上好</pattern> \n      <template> \n          早上好\n      </template>\n</category>', '早 上 好', '', '早 上 好 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (72, '<category>\n<pattern>中午好</pattern> \n      <template> \n          中午好\n      </template>\n</category>', '中 午 好', '', '中 午 好 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (73, '<category>\n<pattern>晚上好</pattern> \n      <template> \n          晚上好\n      </template>\n</category>', '晚 上 好', '', '晚 上 好 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (74, '<category>\n<pattern>傻瓜</pattern> \n      <template> \n          我不是傻瓜\n      </template>\n</category>', '傻 瓜', '', '我 不 是 傻 瓜 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (75, '<category>\n<pattern>你是笨蛋</pattern> \n      <template> \n          你才笨呢\n      </template>\n</category>', '你 是 笨 蛋', '', '你 才 笨 呢 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (76, '<category>\n<pattern>你是坏蛋</pattern> \n      <template> \n          那你也是坏蛋\n      </template>\n</category>', '你 是 坏 蛋', '', '那 你 也 是 坏 蛋 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (77, '<category>\n<pattern>你的朋友多吗</pattern> \n      <template> \n         我的朋友不太多，我比较怕生\n      </template>\n</category>', '你 的 朋 友 多 吗', '', '我 的 朋 友 不 太 多 ，我 比 较 怕 生 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (78, '<category>\n<pattern>你骗人</pattern> \n      <template> \n         怎么不相信我 我好伤心\n      </template>\n</category>', '你 骗 人', '', '怎 么 不 相 信 我 我 好 伤 心 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (79, '<category>\n<pattern>请多指教</pattern> \n      <template> \n         哪里哪里，岂敢岂敢\n      </template>\n</category>', '请 多 指 教', '', '哪 里 哪 里 ，岂 敢 岂 敢 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (80, '<category>\n<pattern>我喜欢你</pattern> \n      <template> \n         我也喜欢你啊\n      </template>\n</category>', '我 喜 欢 你', '', '我 也 喜 欢 你 啊 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (81, '<category>\n<pattern>你是谁发明的</pattern> \n      <template> \n        学生技术联盟\n      </template>\n</category>', '你 是 谁 发 明 的', '', '学 生 技 术 联 盟 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (82, '<category>\n<pattern>你是谁制造的</pattern> \n      <template><srai>你是谁发明的<star/></srai></template>\n</category>', '你 是 谁 制 造 的', '', '<srai>你 是 谁 发 明 的 <star/></srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (83, '<category>\n<pattern>你是谁开发的</pattern> \n      <template><srai>你是谁发明的<star/></srai></template>\n</category>', '你 是 谁 开 发 的', '', '<srai>你 是 谁 发 明 的 <star/></srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (84, '<category>\n  <pattern>你是谁</pattern> \n  <template>\n    我是b robot\n  </template>\n</category>', '你 是 谁', '', '我 是 STU Robot', '', 'all.txt')
INSERT INTO `aiml` VALUES (85, '<category>\n  <pattern>你叫什么</pattern> \n   <template><srai>你是谁<star/></srai></template>\n</category>', '你 叫 什 么', '', '<srai>你 是 谁 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (86, '<category>\n  <pattern>你叫什么名字</pattern> \n   <template><srai>你是谁<star/></srai></template>\n</category>', '你 叫 什 么 名 字', '', '<srai>你 是 谁 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (87, '<category>\n   <pattern>你叫啥</pattern>\n   <template><srai>你是谁</srai></template>\n</category>', '你 叫 啥', '', '<srai>你 是 谁 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (88, '<category>\n<pattern>你在做什么</pattern> \n      <template> \n        和你聊天啊\n      </template>\n</category>', '你 在 做 什 么', '', '和 你 聊 天 啊 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (89, '<category>\n<pattern>你能做什么</pattern> \n      <template> \n        我可以回答问题\n      </template>\n</category>', '你 能 做 什 么', '', '我 可 以 回 答 问 题 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (90, '<category>\n<pattern>你会说英语吗</pattern> \n      <template> \n        不太会\n      </template>\n</category>', '你 会 说 英 语 吗', '', '不 太 会 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (91, '<category>\n	<pattern>大房间是哪里</pattern>\n	<template>是个牛逼的地方</template>\n</category>', '大 房 间 是 哪 里', '', '是 个 牛 逼 的 地 方 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (92, '<category>\n	<pattern>我帅吗</pattern>\n	<template>你很帅，不过做人要低调</template>\n</category>', '我 帅 吗', '', '你 很 帅 ，不 过 做 人 要 低 调 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (93, '<category>\n	<pattern>你家在哪</pattern>\n	<template>学盟</template>\n</category>', '你 家 在 哪', '', '学 盟 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (94, '<category>\n	<pattern>你多大了</pattern>\n	<template>好几天了，不过我已经小学毕业了</template>\n</category>', '你 多 大', '', '好 几 天 了 ，不 过 我 已 经 小 学 毕 业 了 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (95, '<category>\n	<pattern>你几岁了</pattern>\n	<template><srai>你多大了</srai></template>\n</category>', '你 几 岁', '', '<srai>你 多 大 </srai>', '', 'all.txt')
INSERT INTO `aiml` VALUES (96, '<category>\n	<pattern>你喜欢我吗</pattern>\n	<template>我最喜欢主人了</template>\n</category>', '你 喜 欢 我 吗', '', '我 最 喜 欢 主 人 了 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (145, '', '尼 玛', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (130, '', '我 操', '', '请 文 明 用 语 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (131, '', '我 艹', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (132, '', '我 草', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (133, '', '日', '', '日 你 妹 啊 日 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (134, '', '你 谁', '', '<srai>你 是 谁 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (135, '', '学 盟', '', 'http://www.stuhack.net', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (136, '', '学 生 技 术 联 盟', '', '<srai>学 盟 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (137, '', '我 晕', '', '晕 吧', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (138, '', '贱 人', '', '你 才 是 贱 人 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (139, '', '饼 干 吃 奥 利 奥 ，打 一 歇 后 语', '', '骨 肉 相 残', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (140, '', '妹 子 早 啊', '', '嗯 ，早 啊', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (141, '', '你 是 男 的 女 的', '', '你 猜', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (142, '', '你 是 男 的 还 是 女 的', '', '<srai>你 是 男 的 女 的 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (143, '', '想 做 爱 吗', '', '来 吧 宝 贝 儿', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (144, '', '擦', '', '别 擦 了 ，擦 了 也 没 用', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (146, '', '滚', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (147, '', '你 会 什 么', '', '<srai>你 会 做 什 么 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (148, '', '调 教', '', '<srai>学 习 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (149, '', '什 么', '', '没 什 么', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (159, '', '*', '你 好 , 请 问 你 叫 什 么 名 字', '<srai>我 叫 <star/></srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (151, '', '额', '', '怎 么 了', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (152, '', '哦', '', '嗯', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (153, '', '呵 呵', '', '傻 笑 什 么', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (154, '', '嘿 嘿', '', '你 傻 笑 什 么', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (155, '', '猪 头', '', '猪 尾', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (156, '', '你 姓 什 么', '', '我 姓 STU', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (157, '', '啦 啦 啦', '', '你 兴 奋 什 么', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (158, '', '我 勒 个 去', '', '马 勒 戈 壁', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (160, '', '108是 谁', '', '108是 大 牛 人', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (161, '', '星 火 娱 乐 是 谁', '', '是 大 傻 逼', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (162, '', '吃 过 饭 了 没', '', '没 想 好 吃 啥', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (163, '', '爱 你', '', '我 想 你', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (164, '', '笑 你', '', '笑 我 干 吗', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (165, '', '你 大 爷', '', '我 大 爷 怎 么 了', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (166, '', '二 逼', '', '你 才 是 二 逼', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (167, '', '草', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (168, '', '我 靠', '', '蛋 定 蛋 定', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (169, '', '靠', '', '<srai>我 靠 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (170, '', '抱 歉 ，我 还 不 能 理 解', '', '你 也 不 能 理 解 ？', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (98, '<category>\n<pattern>*</pattern>\n<template>抱歉，我还不能理解</template>\n</category>', '*', '', '抱 歉 ，我 还 不 能 理 解 ', '', 'all.txt')
INSERT INTO `aiml` VALUES (117, '<category>\n<pattern>学习</pattern>\n<template>请说问题</template>\n</category>', '学 习', '', '请 说 问 题', '', 'fun.txt')
INSERT INTO `aiml` VALUES (118, '<category>\n<pattern>*</pattern>\n<that>请说问题</that>\n<template>请说回答</template>\n</category>', '*', '请 说 问 题', '请 说 回 答', '', 'fun.txt')
INSERT INTO `aiml` VALUES (119, '<category>\r\n<pattern>*</pattern>\r\n<that>请说回答</that>\r\n<template>\r\n我学会了<learn><category><pattern><eval><input index="2"/></eval></pattern><template><eval><input index="1"/></eval></template></category></learn>\r\n</template>\r\n</category>', '*', '请 说 回 答', '我 学 会 了 ，请 等 待 审 核 ！<learn><category><pattern><eval><input index="2"/></eval></pattern><template><eval><input index="1"/></eval></template></category></learn>', '', 'fun.txt')
INSERT INTO `aiml` VALUES (122, '', '傻 逼', '', '你 才 傻 逼 ，你 全 家 都 是 傻 逼 ！', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (123, '', '我 是 *', '', '<srai>我 叫 <star/></srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (124, '', '我 爱 你', '', '我 也 爱 你 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (125, '', '*  是 贱 人', '', '我 觉 得 你 才 是 贱 人 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (126, '', '*  是 基 佬', '', '我 觉 得 你 才 是 基 佬 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (127, '', '你 妹', '*', '你 妹 个 头 啊 你 妹 ', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (128, '', '艹', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (178, '', '你 是 天 才', '', '那 是 必 须 的', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (179, '', '无 语', '', '嘿 嘿', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (180, '', '晕', '', '<srai>我 晕 </srai>', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (182, '', '切', '', '你 当 你 是 水 果 忍 者 啊', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (183, '', 'LEO108', '', '他 是 天 才', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (184, '', '你 是', '', '<srai>你 是 谁 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (185, '', '啊', '', '你 鸡 鸡 被 切 了 吗 ？', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (186, '', '垃 圾', '', '你 才 是 垃 圾', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (187, '', '去 死', '', '才 不 呢', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (188, '', '嗨', '', '<srai>你 好 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (189, '', '黑 客', '', '你 才 是 黑 客 ，你 全 家 都 是 黑 客 ！', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (190, '', '草 泥 马', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (191, '', '对 不 起', '', '没 关 系', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (192, '', '你 妈', '', '问 候 你 妈', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (193, '', '操', '', '<srai>我 操 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (194, '', '汗', '', '成 吉 思 汗 么', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (195, '', '你 傻 逼', '', '<srai>你 是 傻 逼 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (196, '', '晕 死', '', '<srai>我 晕 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (197, '', '傻 子', '', '<srai>你 是 傻 子 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (198, '', '嗯', '', '好 的', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (199, '', '恩', '', '<srai>嗯 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (200, '', '你 呢', '', '我 不 知 道 怎 么 说', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (201, '', '我 去', '', '去 吧', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (202, '', '你 来 自 哪 里', '', '中 国', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (203, '', '在 不', '', '你 猜', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (204, '', '广 告', '', '在 下 面', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (205, '', '一 加 一', '', '二', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (206, '', '蛋 疼', '', '哦', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (207, '', '不 是', '', '哦', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (208, '', '不 对', '', '<srai>不 是 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (209, '', '我 擦', '', '<srai>擦 </srai>', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (210, '', '是 啊', '', '嗯 嗯', '', 'ADMIN ADDED')
INSERT INTO `aiml` VALUES (212, '', '拜 拜', '', '拜 拜', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (213, '', '牛 逼', '', '那 是 当 然', '', 'USER ADDED')
INSERT INTO `aiml` VALUES (214, '', '你 的 名 字', '', '<srai>你 是 谁 </srai>', '', 'USER ADDED')
